export const WISH_LIST = [
  {
    id: 1,
    url: '#',
    image: '/images/Main/bookCover/cover1.jpg',
    title: '바쁘다 바빠 현대사회',
    author: '각박한 세상',
    price: 9600,
    checked: false,
  },
  {
    id: 2,
    url: '#',
    image: '/images/Main/bookCover/cover2.jpg',
    title: '내 남자친구에게',
    author: '핑클',
    price: 5600,
    checked: false,
  },
  {
    id: 3,
    url: '#',
    image: '/images/Main/bookCover/cover3.jpg',
    title: '여름에 일어나는 전쟁은?',
    author: '더워',
    price: 1600,
    checked: false,
  },
  {
    id: 4,
    url: '#',
    image: '/images/Main/bookCover/cover4.jpg',
    title: '음치를 위한 노래 가이드',
    author: '함부로 마이크 잡지마',
    price: 10600,
    checked: false,
  },
  {
    id: 5,
    url: '#',
    image: '/images/Main/bookCover/cover5.jpg',
    title: '우유가 쓰러지면?',
    author: '아야',
    price: 600,
    checked: false,
  },
  {
    id: 6,
    url: '#',
    image: '/images/Main/bookCover/cover6.jpg',
    title: '소나무가 삐지면?',
    author: '칫솔',
    price: 20700,
    checked: false,
  },
  {
    id: 7,
    url: '#',
    image: '/images/Main/bookCover/cover7.jpg',
    title: '논리적인 사람이 총을 쏘면?',
    author: '타당타당',
    price: 5600,
    checked: false,
  },
  {
    id: 8,
    url: '#',
    image: '/images/Main/bookCover/cover8.jpg',
    title: '딸이 기분이 좋으면?',
    author: '딸기모찌',
    price: 8600,
    checked: false,
  },
  {
    id: 9,
    url: '#',
    image: '/images/Main/bookCover/cover9.jpg',
    title: '신데렐라가 잠을 못자면?',
    author: '모짜렐라',
    price: 4600,
    checked: false,
  },
];
